import Head from 'next/head'
import Sidebar from '../conponents/Sidebar'
const styles = {
  container: `h-full w-full flex bg-[#ffffff]`
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Azaz Web3.0 Online Shop</title>
        <meta name="description" content="Generated by Azaz Web3.0 Online Shop" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />

      
    </div>
  )
}
